name: Generate Artifacts

on:
  push:
    tags:
      - "v*"
    
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shihanng/csvs-to-sqlite-act@v1.0.0
        with:
          cli_args: courses.csv ./outputs/courses.db
          working_directory: ./
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run csvtojson
      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs

